# # spring.application.name=backend_factu
# # Conexión a Postgres
# spring.datasource.url=jdbc:postgresql://localhost:5432/empresas
# spring.datasource.username=brian
# spring.datasource.password=0000

# # JPA / Hibernate
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# # 'update' creará las tablas si faltan, pero ten cuidado con los cambios manuales en SQL
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true


spring.application.name=backend_factu

# Datos extraídos de tu conexión exitosa
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.fchggyrcvyvdkjheelyh
spring.datasource.password=SallyMaria2702#
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true