spring.application.name=backend_factu

# Conexión a Postgres LOCAL
# Cambia 'empresas' por el nombre real de tu DB en pgAdmin
spring.datasource.url=jdbc:postgresql://localhost:5432/empresas?prepareThreshold=0
spring.datasource.username=brian
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

mercadopago.access-token=

# OPTIMIZACIÓN CRÍTICA PARA VELOCIDAD:
# Evita que Hibernate escanee todo el proyecto buscando validadores que no tienes
spring.jpa.properties.javax.persistence.validation.mode=none
server.max-http-request-header-size=40KB

app.ngrok-url=https://postabdominal-yosef-fordless.ngrok-free.dev


